### ISSUE TITLE
Install error 

### ISSUE THREAD

**Issue by jlmarr10824** [erikrose/peep#102]
This is for a dxd/es snapshot downloaded today, 13-Jul-15.

(pypyenv)[cyli6s85]/scratch/dxr-es-based> dxr-es/peep.py install -r dxr-es/requirements.txt

Oh no! Peep had a problem while trying to do stuff. Please write up a bug report
with the specifics so we can fix it:

https://github.com/erikrose/peep/issues/new

Here are some particulars you can copy and paste into the bug report:

---
peep: (2, 4, 1)
python: '2.7.5 (default, Jun 17 2014, 18:11:42) \n[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)]'
pip: '7.0.1'
Command line:  ['dxr-es/peep.py', 'install', '-r', 'dxr-es/requirements.txt']
Traceback (most recent call last):
  File "dxr-es/peep.py", line 901, in <module>
    exit(main())
  File "dxr-es/peep.py", line 873, in main
    return commands[argv[1]](argv[2:])
  File "dxr-es/peep.py", line 833, in peep_install
    for path in req_paths))
  File "dxr-es/peep.py", line 833, in <genexpr>
    for path in req_paths))
  File "dxr-es/peep.py", line 794, in downloaded_reqs_from_path
    finder = package_finder(argv)
  File "dxr-es/peep.py", line 335, in package_finder
    return PackageFinder(index_urls=index_urls, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_wheel'

**Comment by erikrose** [comment]
Your version of pip is too new to be used with peep. We're working on it. In the meantime, you can either downgrade to pip <7.0, or you can throw security to the wind and call pip instead of peep.
