### ISSUE TITLE
Unexpected keyword argument : 'use_wheel'

### ISSUE THREAD

**Issue by Killthebug** [erikrose/peep#106]
This is the error that showed up when I was running peep.sh to install the requirements for kitsune in the virtual env. What do you think might be the issue ?
Running on Fedora 22.
```
peep: (2, 4, 0)
python: '2.7.10 (default, Jul  5 2015, 14:15:43) \n[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)]'
pip: '7.1.2'
Command line:  ['./scripts/peep.py', 'install', '-r', 'requirements/default.txt']
Traceback (most recent call last):
  File "./scripts/peep.py", line 902, in <module>
    exit(main())
  File "./scripts/peep.py", line 874, in main
    return commands[argv[1]](argv[2:])
  File "./scripts/peep.py", line 834, in peep_install
    for path in req_paths))
  File "./scripts/peep.py", line 834, in <genexpr>
    for path in req_paths))
  File "./scripts/peep.py", line 795, in downloaded_reqs_from_path
    finder = package_finder(argv)
  File "./scripts/peep.py", line 335, in package_finder
    return PackageFinder(index_urls=index_urls, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_wheel'
```

**Comment by willkg** [comment]
Two things:

First, if you look at the kitsune docs, they say to run it like this:

```
$ ./peep.sh install -r requirements/default.txt
```

http://kitsune.readthedocs.org/en/latest/hacking_howto.html#python-packages

Second, peep doesn't work with versions of pip past 6. this is covered by a bunch of issues and pr #94 

Best to use an older version of pip.

**Comment by Killthebug** [comment]
@willkg Yes, this is regarding kitsune and that is how I ran it, yet running into these issues.

I think I'll try doing the same using an older version of pip.

**Comment by willkg** [comment]
@mythmon is on PTO and i'm traveling, but usually there are people in `#sumodev` on irc.mozilla.org that can help with issues like the ones you're having. There's also the mailing list.

http://kitsune.readthedocs.org/en/latest/contactus.html
