### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by kman261** [erikrose/peep#134]
I am trying to install for the first time on my mail server (iRedmail installation).  Below are the particulars:
 cat /etc/*release*
CentOS release 6.7 (Final)
0.9.4
CentOS release 6.7 (Final)
CentOS release 6.7 (Final)
cpe:/o:centos:linux:6:GA

----------------------------------------
Cleaning up...
Command /root/.local/share/letsencrypt/bin/python -c "import setuptools;__file__='/tmp/pip-cOhSWS-build/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-58TTY1-record/install-record.txt --single-version-externally-managed --install-headers /root/.local/share/letsencrypt/include/site/python2.7 failed with error code 1 in /tmp/pip-cOhSWS-build

Oh no! Peep had a problem while trying to do stuff. Please write up a bug report
with the specifics so we can fix it:

https://github.com/erikrose/peep/issues/new

Here are some particulars you can copy and paste into the bug report:

---
peep: (3, 1, 1)
python: '2.7.5 (default, Jul 10 2014, 16:10:08) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]'
pip: '1.4.1'
Command line:  ['/tmp/tmp.macS2WPQVN/peep.py', 'install', '-r', '/tmp/tmp.macS2WPQVN/letsencrypt-auto-requirements.txt']
Traceback (most recent call last):
  File "/tmp/tmp.macS2WPQVN/peep.py", line 967, in <module>
    exit(main())
  File "/tmp/tmp.macS2WPQVN/peep.py", line 939, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.macS2WPQVN/peep.py", line 884, in peep_install
    req.install()
  File "/tmp/tmp.macS2WPQVN/peep.py", line 652, in install
    run_pip(['install'] + other_args + ['--no-deps', '-U', archive_path])
  File "/tmp/tmp.macS2WPQVN/peep.py", line 206, in run_pip
    status_code = pip.main(initial_args)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/__init__.py", line 148, in main
    return command.main(args[1:], options)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/basecommand.py", line 169, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 75: ordinal not in range(128)

---

Thanks,
Dave
kman261@dkcc.com

**Comment by erikrose** [comment]
Filed at https://github.com/letsencrypt/letsencrypt/issues/2588, and we have a fix on that way. Thanks for the report!

**Comment by kman261** [comment]
Hi Erik,

 

I am not sure if this will help you or not.  I was just able to get my iRedmail server to work.  This is how I had to do it:

 

I was able to install letsencrypt on two other Centos servers successfully since this issue (web2).  This is my script:

#setup centos 6.7

 

yum -y install centos-release-SCL

yum -y update

yum -y install scl-utils python27 python27-scldevel

scl enable python27 bash

 

yum -y install git

cd

git clone https://github.com/letsencrypt/letsencrypt

cd letsencrypt

./letsencrypt-auto --help

 

mkdir /var/www/.well-known

mkdir /var/www/.well-known/acme-challenge/

chown -R apache:apache /var/www/

 

service httpd stop

./letsencrypt-auto certonly --test-cert --standalone -d my.domain.com

service httpd start

echo "remove --test-cert flag after success"

 

Doing this on my iRedmail server (mx), (also Centos 6.7), I continued to get the peep error:

peep: (3, 1, 1)

python: '2.7.5 (default, Jul 10 2014, 16:10:08) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]'

pip: '1.4.1'

 

I did a search for pip on a successful server and found a directory 

/root/.local/share/letsencrypt/ 

[root@web2 /]# find / -name pip

/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip

/root/.local/share/letsencrypt/bin/pip

 

I copied the directory from the good server to the mail server (which had no letsencrypt directory),

[root@mx ~]# cd /root/.local/share/

[root@mx ~]# scp -r root@192.168.1.240:/root/.local/share/letsencrypt/ .

 

And was then able to get a cert issued using letsencrypt-auto.  I hope that helps you.  

 

[root@mx ~]# /root/.local/share/letsencrypt/bin/pip -V

pip 1.4.1 from /root/.local/share/letsencrypt/lib64/python2.7/site-packages (python 2.7)

 

If you do find this useful, and figure out a fix/workaround, let me know and I will post the above script to the iRedmail users for installation on Centos 6.

 

Thanks for letsencrypt !!  It is wonderful.  

 

Dave

**Comment by erikrose** [comment]
We just went ahead and bundled a bootstrapping script that installs a recent version of pip, which should dodge all those old pip bugs like the one you encountered. Thanks anyway, though!
