### ISSUE TITLE
peep error installing oneanddone requirements

### ISSUE THREAD

**Issue by rbillings** [erikrose/peep#135]
./bin/peep.py install -r requirements.txt 
Handy details provided by the error:

peep: (2, 4, 0)
python: '2.7.9 (v2.7.9:648dcafa7e5f, Dec 10 2014, 10:10:46) \n[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)]'
pip: '8.1.0'
Command line:  ['./bin/peep.py', 'install', '-r', 'requirements.txt']
Traceback (most recent call last):
  File "./bin/peep.py", line 902, in <module>
    exit(main())
  File "./bin/peep.py", line 874, in main
    return commands[argv[1]](argv[2:])
  File "./bin/peep.py", line 834, in peep_install
    for path in req_paths))
  File "./bin/peep.py", line 834, in <genexpr>
    for path in req_paths))
  File "./bin/peep.py", line 795, in downloaded_reqs_from_path
    finder = package_finder(argv)
  File "./bin/peep.py", line 335, in package_finder
    return PackageFinder(index_urls=index_urls, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_wheel'

**Comment by edmorley** [comment]
oneanddone is using an out of date version of peep, which doesn't include #94:
https://github.com/mozilla/oneanddone/blob/7195406ba41fa8e2178b06a9ee1c475f3322749e/bin/peep.py#L108

Newer versions support pip 7.x/8.x:
https://github.com/erikrose/peep#version-history
