### ISSUE TITLE
letsencrypt-auto certonly

### ISSUE THREAD

**Issue by ahelhot** [erikrose/peep#138]
yesterday i run this tool without probles with command:

`
./letsencrypt-auto certonly --webroot --test-cert -w /var/www/more/data/www/example.com/ -d example.com
`

this not work, url like example.com/.well-known/acme.../ - not oppened in browser.

today i try to change webroot (i have cakephp, and it webroot in example.com/srv/webroot)

and run command

`
./letsencrypt-auto certonly --webroot --test-cert -w /var/www/more/data/www/example.com/srv/webroot -d example.com
`

this is output by letsencrypt-auto

`
peep: (3, 1, 1)
python: '2.6.6 (r266:84292, Jul 23 2015, 15:22:56) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]'
pip: '1.4.1'
Command line:  ['/tmp/tmp.gza8zc7HBY/peep.py', 'install', '-r', '/tmp/tmp.gza8zc7HBY/letsencrypt-auto-requirements.txt']
Traceback (most recent call last):
  File "/tmp/tmp.gza8zc7HBY/peep.py", line 967, in <module>
    exit(main())
  File "/tmp/tmp.gza8zc7HBY/peep.py", line 939, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.gza8zc7HBY/peep.py", line 864, in peep_install
    for path in req_paths))
  File "/tmp/tmp.gza8zc7HBY/peep.py", line 864, in <genexpr>
    for path in req_paths))
  File "/tmp/tmp.gza8zc7HBY/peep.py", line 841, in downloaded_reqs_from_path
    _parse_requirements(path, finder)]
  File "/tmp/tmp.gza8zc7HBY/peep.py", line 422, in __init__
    self.__class__ = self._class()
  File "/tmp/tmp.gza8zc7HBY/peep.py", line 701, in _class
    if self._actual_hash() not in self._expected_hashes():
  File "/tmp/tmp.gza8zc7HBY/peep.py", line 331, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.gza8zc7HBY/peep.py", line 657, in _actual_hash
    return hash_of_file(join(self._temp_path, self._downloaded_filename()))
  File "/tmp/tmp.gza8zc7HBY/peep.py", line 331, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.gza8zc7HBY/peep.py", line 615, in _downloaded_filename
    file_path = self._download(link)
  File "/tmp/tmp.gza8zc7HBY/peep.py", line 577, in _download
    response = opener(urlparse(url).scheme != 'http').open(url)
  File "/usr/lib64/python2.6/urllib2.py", line 391, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.6/urllib2.py", line 409, in _open
    '_open', req)
  File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.6/urllib2.py", line 1198, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib64/python2.6/urllib2.py", line 1163, in do_open
    r = h.getresponse()
  File "/usr/lib64/python2.6/httplib.py", line 1012, in getresponse
    response.begin()
  File "/usr/lib64/python2.6/httplib.py", line 404, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python2.6/httplib.py", line 368, in _read_status
    raise BadStatusLine(line)
BadStatusLine
---
`

Run with logs:

`
Bootstrapping dependencies for RedHat-based OSes...
yum is /usr/bin/yum
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.h1host.ru
 * epel: mirror.logol.ru
 * extras: mirror.h1host.ru
 * updates: mirror.h1host.ru
Package python-2.6.6-64.el6.x86_64 already installed and latest version
Package python-devel-2.6.6-64.el6.x86_64 already installed and latest version
Package python-virtualenv-1.10.1-1.el6.noarch already installed and latest version
Package python-tools-2.6.6-64.el6.x86_64 already installed and latest version
Package python-pip-7.1.0-1.el6.noarch already installed and latest version
Nothing to do
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.h1host.ru
 * epel: mirror.logol.ru
 * extras: mirror.h1host.ru
 * updates: mirror.h1host.ru
Package gcc-4.4.7-16.el6.x86_64 already installed and latest version
Package dialog-1.1-9.20080819.1.el6.x86_64 already installed and latest version
Package augeas-libs-1.0.0-10.el6.x86_64 already installed and latest version
Package openssl-1.0.1e-42.el6_7.4.x86_64 already installed and latest version
Package openssl-devel-1.0.1e-42.el6_7.4.x86_64 already installed and latest version
Package libffi-devel-3.0.5-3.2.el6.x86_64 already installed and latest version
Package redhat-rpm-config-9.0.3-44.el6.centos.noarch already installed and latest version
Package ca-certificates-2015.2.4-65.0.1.el6_6.noarch already installed and latest version
Nothing to do
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirror.h1host.ru
 * epel: mirror.logol.ru
 * extras: mirror.h1host.ru
 * updates: mirror.h1host.ru
Package 1:mod_ssl-2.2.15-47.el6.centos.3.x86_64 already installed and latest version
Nothing to do
Checking for new version...
Creating virtual environment...
Installing Python packages...
Had a problem while downloading and verifying Python packages:
Downloading argparse==1.4.0 (70K)...
Downloading pycparser==2.14 (223K)...
Downloading cffi==1.4.2 (365K)...
Downloading ConfigArgParse==0.10.0 (36K)...
Downloading configobj==5.0.6 (33K)...
Downloading cryptography==1.2.3 (373K)...
Downloading enum34==1.1.2 (46K)...
Downloading funcsigs==0.4 (25K)...
Downloading idna==2.0 (135K)...
Downloading ipaddress==1.0.16 (31K)...
Oh no! Peep had a problem while trying to do stuff. Please write up a bug report
`

p.s. sorry for my engish

**Comment by erikrose** [comment]
It's probably a transient network error. Can you try again and reopen if it still goes wrong?
