### ISSUE TITLE
"KeyError: None" when there's no req.name

### ISSUE THREAD

**Issue by willkg** [erikrose/peep#57]
With this requirements file:

```
http://people.mozilla.org/~wkahngreene/pep8/pep8-1.6.0a0-willkg.1.tar.gz
```

I get this:

```
<pep-test> saturn2 ~/tmp/pep8-test> ./peep install -r reqs.txt 

The following packages had no hashes specified in the requirements file, which
leaves them open to tampering. Vet these packages to your satisfaction, then
add these "sha256" lines like so:

Traceback (most recent call last):
  File "./peep", line 486, in <module>
    exit(main())
  File "./peep", line 478, in main
    return commands[argv[1]](argv[2:])
  File "./peep", line 442, in peep_install
    print('# sha256: %s' % downloaded_hashes[req.name])
KeyError: None
```

That's with Python 2.7, pip 1.5.6 and peep 1.3.0.

I'm not entirely sure what's going on, but I suspect req.name is junk or there's nothing in downloaded_hashes.

**Comment by erikrose** [comment]
Fixed at some point. Peep 2.1 does this:

    % ./peep.py install -r reqs.txt


    The following requirements could not be processed:

    * Unable to determine package name from URL http://people.mozilla.org/~wkahngreene/pep8/pep8-1.6.0a0-willkg.1.tar.gz; add #egg=

    -------------------------------
    Not proceeding to installation.
