### ISSUE TITLE
"ImportError: No module named log" when using peep with newer versions of pip

### ISSUE THREAD

**Issue by jgmize** [erikrose/peep#65]
The pip.log module was removed in favor of the stdlib logger in https://github.com/pypa/pip/pull/2008 but it is imported in https://github.com/erikrose/peep/blob/master/peep.py#L74 in order to clear out the registrations in the logger singleton in https://github.com/erikrose/peep/blob/master/peep.py#L130. I'll submit a PR that adds error handling to the import shortly.

**Comment by erikrose** [comment]
Correct me if I'm wrong, but I think those merges fix this.

**Comment by willkg** [comment]
Yup! This is fixed now.
