### ISSUE TITLE
travis should run tests in all environment combinations

### ISSUE THREAD

**Issue by willkg** [erikrose/peep#67]
Travis should run the tests in all the environment combinations. Plus it'd be nice to have a way to make sure `tox.ini` and `.travis.yml` are in sync.

**Comment by erikrose** [comment]
Worst case, it could run a pared-down tox config that would take care of different pip versions, while Travis itself took care of Python versions. That's essentially what http://jsatt.com/blog/using-tox-with-travis-ci-to-test-django-apps/ does.

**Comment by erikrose** [comment]
This should solve all our problems: https://github.com/msabramo/python-panci. We don't even necessarily have to use it; following the pattern of its multi-python-version example travis configs might be enough.
