### ISSUE TITLE
No output while downloading files

### ISSUE THREAD

**Issue by mythmon** [erikrose/peep#72]
When peep is run, it seems to just sit there for a bit, while it churns away downloading files. It would be nice to at least get a message that says "Downloading files", but even better to print out each package as it is downloaded. Even better than that would be a progress bar, but that might be asking for too much.

**Comment by willkg** [comment]
+1 to this.

I mentioned this on IRC the other day, but I was using an old version of peep and didn't want to write up an issue without first updating.

Anyhow, the problem I have with the current situation is that it seems like peep has hung. It takes several minutes to install packages for fjord during which time it shows nothing at all.

I'm ok with any of @mythmon's ideas. Other than solving the immediate problem of "it's just sitting there", are there other informational problems we can solve here?

**Comment by erikrose** [comment]
Wish granted! :-D

**Comment by erikrose** [comment]
Give it a try, and let me know if it works okay for you. Used with pip 6.0 and up, you get the full nice-progress-bar treatment. If it checks out okay for you, I'll cut a release.

**Comment by mythmon** [comment]
This mostly works. Nice progress bars on 6.0, and a list of downloadeds on <6.0. It had the confusing behavior of showing progress bars for some PyPI downloads, but only a spinner for GitHub tarballs. I suspect that GitHub isn't providing the right kinds of hints to the downloader, but I'm not sure.

Then I tried to run it like `./peep.py install -r ... | cat`. This mimics running in non-interactive settings (like Travis). It had the old behavior of staying silent until all the downloads are complete. This was true on both versions I tested.

This helps a lot for interactive use, and the non-interactive case is fine. It would be nice to get downloads one line at a time on Travis, but I think that if someone is watching Travis download files, maybe they need to get a Rubik's cube. :smile:

I say :shipit:.

**Comment by erikrose** [comment]
Cool. Does pip show DL progress on Travis? I'm pretty much just calling into their code.

**Comment by erikrose** [comment]
And yes, GitHub doesn't provide a content-length:

```
[('x-xss-protection', '1; mode=block'),
 ('content-disposition', 'attachment; filename=django-master.zip'),
 ('x-content-type-options', 'nosniff'),
 ('content-security-policy', "default-src 'none'"),
 ('strict-transport-security', 'max-age=31536000'),
 ('vary', 'Authorization,Accept-Encoding'),
 ('connection', 'close'),
 ('etag', '"a53541852d5601232899e54d66e623bc163c6dc2"'),
 ('date', 'Mon, 02 Feb 2015 16:49:29 GMT'),
 ('x-frame-options', 'deny'),
 ('content-type', 'application/zip'),
 ('access-control-allow-origin', 'https://render.githubusercontent.com')]
```

**Comment by willkg** [comment]
This works great for me. Thank you!
