### ISSUE TITLE
Example of requirements file with sha hashes?

### ISSUE THREAD

**Issue by dtheodor** [erikrose/peep#73]
I cannot find any usage example of a requirements file with sha hashes included.

Apart from how to use `peep`, this is the second main thing I expected to see in the readme.

**Comment by willkg** [comment]
If you follow the "Switching to Peep" steps, it walks through using peep to add the sha hashes to the requirements file and has sample output which is what your requirements file should look like.

Further down the file, there are examples of what a github tarball/zip urls look like and examples of how to have multiple hashes in the same requirements file.

That's pretty much it--there's nothing additionally fancy how it should look.

Does that help at all? If not, can you be more specific about what you're looking for?

**Comment by dtheodor** [comment]
Added the example I was looking for.

**Comment by erikrose** [comment]
Fixed with #74.
