### ISSUE TITLE
Duplicate #egg=foo appended to URLs in missing requirements output

### ISSUE THREAD

**Issue by edmorley** [erikrose/peep#76]
The requirements file entry:
```
https://github.com/abourget/gevent-socketio/archive/0f9bd2744af033b7cba57bfd5b82106592e9f667.zip#egg=gevent-socketio
```

The ``peep install -r requirements.txt`` output:
```bash
...
# sha256: 3kZ6F0_BamhBlMUri3Tmfcy06re3kuQ7Yf0J8TTWnmA
https://github.com/abourget/gevent-socketio/archive/0f9bd2744af033b7cba57bfd5b82106592e9f667.zip#egg=gevent-socketio#egg=gevent-socketio
...
```
Note the ``#egg=gevent-socketio#egg=gevent-socketio``.

Looks like there is an issue here:
https://github.com/erikrose/peep/blob/c5c103f9b0/peep.py#L686

**Comment by willkg** [comment]
What version of peep and pip are you using?

**Comment by edmorley** [comment]
I'm working on a fix locally, I'll open a PR.

**Comment by willkg** [comment]
Which versions of peep and pip are you using?

**Comment by edmorley** [comment]
pip 6.0.8 & peep 2.2 (plus from master).
Though the bug is quite clear when reading the code - the versions are irrelevant :-)

**Comment by edmorley** [comment]
The problem is that:
```
if self._name() not in filename_from_url(self._url())
```
is always going to be true, since:
``filename_from_url(https://github.com/foo/bar.zip#egg=baz)``
always returns ``bar.zip``, since:
```
>>> urlparse('https://github.com/foo/bar.zip#egg=baz').path
'/foo/bar.zip'
``
See:
https://docs.python.org/2/library/urlparse.html

**Comment by edmorley** [comment]
Anyway, we can safely remove the appending, since peep already enforces that ``#egg=foo`` is appended to URLs, so I've just removed those lines in the PR.
