### ISSUE TITLE
Add license text to the top of peep.py

### ISSUE THREAD

**Issue by edmorley** [erikrose/peep#79]
The readme suggests embedding peep.py directly in other source repos:
https://github.com/erikrose/peep#embedding

In Treeherder's case, we've put it in our bin directory.

However the peep license requires that we distribute a copy of the license with peep, but I'd really quite like to avoid having the LICENSE file cluttering up our bin directory.

Perhaps it's worth just adding a copy of the licence text to the top of peep.py, so embedders only have one file to include? (And can use the file verbatim, rather than needing to append the licence to the top of it themselves manually) :-)

**Comment by erikrose** [comment]
I actually just did this yesterday, in response to willkg noticing the same thing! :-) https://github.com/erikrose/peep/commit/e0af1546312197377d3fa556e22a34969a6a750a

**Comment by edmorley** [comment]
Ah great, thank you :-)
