### ISSUE TITLE
Peep, URLs in requirements files & Travis cache invalidation

### ISSUE THREAD

**Issue by edmorley** [erikrose/peep#91]
We have several entries in the Treeherder requirements file which refer to a github zip archive rather than a pypi version release:
https://github.com/mozilla/treeherder/blob/c7205463351910f4c63f43f349975502a4a8aa7d/requirements/common.txt#L60

This means peep tries to download it on every Travis run, which doesn't actually take long, however it then means that changes are detected in the cached virtualenv directory, causing a 60s file upload to S3 for the new cache. eg:
https://travis-ci.org/mozilla/treeherder/builds/59898650

Strangely, only one of the ZIP-using packages shows up in the "changed files" list at the bottom of the Travis log:
```bash
store build cache
change detected: /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/datasource/DataHub.py
changes detected, packing new archive
uploading archive
```

So (a) do you know what might be different about this package to cause changes to be found, and (b) is there any way I can either get peep to not re-install the package (eg instead of using just "#egg=datasource" on the end of the URL, add a feature to allow using "#egg=datasource-0.6"?) or else can I trick Travis into playing ball?

**Comment by edmorley** [comment]
The package in question is:
https://github.com/jeads/datasource

I guess one explanation might be that Travis only shows the first changed file in the cache, and then just skips to the upload rather than checking the rest (ie all of the URL packages might be changed, but datasource was just the first seen).

Ideally we'd just upload datasource to pypi, however (a) it's not my package and the owner has left Mozilla, (b) there is already a package on pypi with the same name, so I'm going to have to change it, and (c) we're wanting to move off this package in the next 6 months anyway.

**Comment by edmorley** [comment]
> eg instead of using just "#egg=datasource" on the end of the URL, add a feature to allow using "#egg=datasource-0.6"

ie make _is_always_unsatisfied() less strict, if we can extract a version number from the ```#egg=foo-0.9```:
https://github.com/erikrose/peep/blob/62e83473dc537fa3b998d6b031ad18729e0ef244/peep.py#L389

**Comment by erikrose** [comment]
Some notes from IRC:
* Well, the -x.y would not be compatible with existing pip behavior.
* Unfortunately, the hard bit is that, once installed, the tarball is obliterated. It isn't anywhere in the venv. You'd have to define a way to unpack the new tarball and compare its contents with what's currently installed in the cached venv. And, unless it's a wheel, installing runs arbitrary code, so that's hard.
* Let me sketch something crazy: You could wrap peep in a tool that caches the old reqs file and compares it with the current one. Then, have it remove all lines except the new ones, and install just those new packages into the existing venv.

**Comment by edmorley** [comment]
Yeah I wasn't meaning actually comparing the tarballs, I was meaning cheating and just trusting the user provided string in the reqs file.

This all said, I guess it's such an edge case (using a tarball for something that does update it's versions properly but isn't on pypi) that perhaps I should just hack around this by setting the mtime in the new Travis before_cache step (only just seen https://github.com/travis-ci/docs-travis-ci-com/commit/088be0f8de1c45135bcfa6d3b48ee0a561448716)

**Comment by edmorley** [comment]
Oh wait, I'd missed the is_git_sha() part - ah I thought this applied to all URL-specified requirements, but it's only those with a SHA for a filename. That's easy then - we'll just make sure there is a Github release zip available for this package, and we won't have to use the SHA :-)

I might add something to the docs to make this clearer.

**Comment by erikrose** [comment]
Ha. :-) I was never too enthusiastic about special-casing the GH SHAs, but it seemed to fill an important niche for Mozilla and probably wouldn't surprise anybody.

**Comment by edmorley** [comment]
The current readme says:
```If a package is already present--which might be the case if you're installing
  into a non-empty virtualenv--Peep doesn't bother downloading or building it
  again.```

Perhaps adding an "except in the case of URLs that contain SHA-like filenames (eg Github revision source zips)", might be clearer?

**Comment by erikrose** [comment]
Yes, and we should explain why we make the exception, if we don't do it elsewhere: because people don't update the version number with every commit.
