### ISSUE TITLE
pip 7.0.0+ breaks peep

### ISSUE THREAD

**Issue by meejah** [erikrose/peep#99]
There is no longer a ``use-wheel`` option in pip 7+ which peep seems to always be passing to PackageFinder. (The equivalent to ``--no-use-wheel`` is now ``--no-binary=:all:`` I believe).

I'm not sure if it's best to make new-peep depend on pip 7+, or to try some shenanigans to support both...

**Comment by willkg** [comment]
Pretty sure this is covered by #95 and #96.

If not, please comment and I can re-open it.
